language: objective-c
before_script:
    - brew update
    - brew install xctool && brew cleanup xctool
script:
    - cd NitroUIColorCategories
    - pod install
    - xctool -workspace NitroUIColorCategories.xcworkspace -sdk iphonesimulator -scheme NitroUIColorCategories test
