platform :ios, '4.3'

target :NitroUIColorCategories do
    pod 'NitroMath', '~> 1.1.0'
    pod 'NitroNSDictionaryCategories', '~> 1.1.0'
end

target :NitroUIColorCategoriesTests do
    pod 'NitroMath', '~> 1.1.0'
end
